const antThemes = {
  Accordion: require('antd-mobile/lib/accordion/style/index.native'),
  ActionSheet: require('antd-mobile/lib/action-sheet/style/index.native'),
  ActivityIndicator: require('antd-mobile/lib/activity-indicator/style/index.native'),
  Badge: require('antd-mobile/lib/badge/style/index.native'),
  Button: require('antd-mobile/lib/button/style/index.native'),
  Card: require('antd-mobile/lib/card/style/index.native'),
  Carousel: require('antd-mobile/lib/carousel/style/index.native'),
  Checkbox: require('antd-mobile/lib/checkbox/style/index.native'),
  Grid: require('antd-mobile/lib/grid/style/index.native'),
  ImagePicker: require('antd-mobile/lib/image-picker/style/index.native'),
  InputItem: require('antd-mobile/lib/input-item/style/index.native'),
  List: require('antd-mobile/lib/list/style/index.native'),
  Modal: require('antd-mobile/lib/modal/style/index.native'),
  NoticeBar: require('antd-mobile/lib/notice-bar/style/index.native'),
  Pagination: require('antd-mobile/lib/pagination/style/index.native'),
  Picker: require('antd-mobile/lib/picker/style/index.native'),
  DatePicker: require('antd-mobile/lib/picker/style/index.native'),
  Progress: require('antd-mobile/lib/progress/style/index.native'),
  Radio: require('antd-mobile/lib/radio/style/index.native'),
  Result: require('antd-mobile/lib/result/style/index.native'),
  SearchBar: require('antd-mobile/lib/search-bar/style/index.native'),
  SegmentedControl: require('antd-mobile/lib/segmented-control/style/index.native'),
  Slider: require('antd-mobile/lib/slider/style/index.native'),
  Steps: require('antd-mobile/lib/steps/style/index.native'),
  Stepper: require('rmc-input-number/lib/styles'),
  TabBar: require('antd-mobile/lib/tab-bar/style/index.native'),
  Tabs: require('antd-mobile/lib/tabs/style/index.native'),
  Tag: require('antd-mobile/lib/tag/style/index.native'),
  TextareaItem: require('antd-mobile/lib/textarea-item/style/index.native'),
  Toast: require('antd-mobile/lib/toast/style/index.native'),
};

export default antThemes;
